;[pytest]
;
;addopts = --headed
;          --browser=chromium
;          #--screenshots=only-on-failure
;          --video=retain-on-failure
;          --tracing=retain-on-failure
;          --html=report.html --capture=tee-sys